steps:

  # Docker Build and Tag to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Docker Build

  # Docker Push to GCR
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
    id: Docker Push
  
    # Access the database configuration from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret=plum-database-config > /workspace/database.env
      source /workspace/database.env

  # Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'plum-service'  # Replace with the desired Cloud Run service name
    - '--image'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA' 
    - '--region'
    - 'us-central1'  # Replace with your desired region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Optional: remove if you want to require authentication
    - '--port'
    - '80'
    - '--args'
    - 'web'
    - '--add-cloudsql-instances'
    - 'my-kubernetes-project-393103:us-central1:plum-instance'  # Replace with your Cloud SQL instance details
    - '--env-vars-file'
    - '/workspace/database.env'

# This ensures the image is available in Cloud Build's cache for faster builds
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'

substitutions:
  _GCR_HOSTNAME: gcr.io
  _IMAGE_NAME: plum 
  _SHORT_SHA: $SHORT_SHA  
